import AlKitab from "./assets/Al Kitab.png"
export const AllProjects = [
    {
        name: "Al Kitab",
        type: "Mobile App",
        lang: "Flutter",
        img: AlKitab,
        gitlink: "https://github.com/humamchoudhary",
        demolink: "https://github.com/humamchoudhary",
    },
    {
        name: "Al Kitab",
        type: "Mobile App",
        lang: "Flutter",
        img: AlKitab,
        gitlink: "https://github.com/humamchoudhary",
        demolink: "https://github.com/humamchoudhary",
    },
    {
        name: "Al Kitab",
        type: "Mobile App",
        lang: "Flutter",
        img: AlKitab,
        gitlink: "https://github.com/humamchoudhary",
        demolink: "https://github.com/humamchoudhary",
    },
    {
        name: "Al Kitab",
        type: "Mobile App",
        lang: "Flutter",
        img: AlKitab,
        gitlink: "https://github.com/humamchoudhary",
        demolink: "https://github.com/humamchoudhary",
    },
    {
        name: "Al Kitab",
        type: "Mobile App",
        lang: "Flutter",
        img: AlKitab,
        gitlink: "https://github.com/humamchoudhary",
        demolink: "https://github.com/humamchoudhary",
    },
    {
        name: "Al Kitab",
        type: "Mobile App",
        lang: "Flutter",
        img: AlKitab,
        gitlink: "https://github.com/humamchoudhary",
        demolink: "https://github.com/humamchoudhary",
    },

]
export const Projects = [
    {
        name: "Al Kitab",
        type: "Mobile App",
        lang: "Flutter",
        img: AlKitab,
        gitlink: "https://github.com/humamchoudhary",
        demolink: "https://github.com/humamchoudhary",
    },
    {
        name: "Al Kitab",
        type: "Mobile App",
        lang: "Flutter",
        img: AlKitab,
        gitlink: "https://github.com/humamchoudhary",
        demolink: "https://github.com/humamchoudhary",
    },
    {
        name: "Al Kitab",
        type: "Mobile App",
        lang: "Flutter",
        img: AlKitab,
        gitlink: "https://github.com/humamchoudhary",
        demolink: "https://github.com/humamchoudhary",
    },
    {
        name: "Al Kitab",
        type: "Mobile App",
        lang: "Flutter",
        img: AlKitab,
        gitlink: "https://github.com/humamchoudhary",
        demolink: "https://github.com/humamchoudhary",
    },
    {
        name: "Al Kitab",
        type: "Mobile App",
        lang: "Flutter",
        img: AlKitab,
        gitlink: "https://github.com/humamchoudhary",
        demolink: "https://github.com/humamchoudhary",
    },
    {
        name: "Al Kitab",
        type: "Mobile App",
        lang: "Flutter",
        img: AlKitab,
        gitlink: "https://github.com/humamchoudhary",
        demolink: "https://github.com/humamchoudhary",
    },

]